### ISSUE TITLE
FWJR performance documentation

### ISSUE THREAD

**Issue by nilsvu** [dmwm/WMArchive#216]
As discussed before, I need to make sense of the FWJR performance data to present them properly in the visualizations. Could you provide documentation on as much data as possible in the FWJR data structure?

You can refer to [this sample FWJR](https://github.com/knly/WMArchiveAggregation/blob/master/sample_data/FWJR.json).
- Most importantly I refer to the data in `steps.performance` such as this:
  
  ```
  "performance" : {
      "multicore" : {
      },
      "storage" : {
          "writeTotalMB" : 2127.67,
          "readPercentageOps" : 1.2768,
          "readAveragekB" : 4010.8291593,
          "readTotalMB" : 3125.62663,
          "readNumOps" : 625,
          "readCachePercentageOps" : 0,
          "readMBSec" : 0.00019514828571,
          "readMaxMSec" : 611502,
          "readTotalSecs" : 0,
          "writeTotalSecs" : 10169000
      },
      "cpu" : {
          "TotalJobCPU" : 165155,
          "EventThroughput" : 0.0644757,
          "AvgEventTime" : 59.1134,
          "MaxEventTime" : 2066.86,
          "TotalJobTime" : 57181.8,
          "TotalLoopCPU" : 165142,
          "MinEventTime" : 0.205815
      },
      "memory" : {
          "PeakValueRss" : 3350.23,
          "PeakValueVsize" : 4157.39
      }
  }
  ```
- The second important part of the FWJR data to document are the **exit codes** in `steps.errors.exitCode`, e.g. in [this sample FWJR](https://github.com/dmwm/WMArchive/blob/master/test/data/samples/ProcessingFailedFwjr.json).

**Comment by vkuznet** [comment]
@ticoann , @amaltaro , Seangchan, Alan, could you please take care of this issue. Nils needs proper documentation on parameter values in order to make presentation layer. Please don't put it aside for too long since Nils time is limited by end of September and he need time to implement this after you provide documentation.

**Comment by amaltaro** [comment]
@knly @vkuznet what especifically you would like to know? The metrics that we have in the FJR and what are they (and if they are important to aggregate or not)? I'll look at it tomorrow

**Comment by nilsvu** [comment]
@amaltaro yes exactly, specifically what each value represents. For some, an indication is given by their key, e.g. `writeTotalMB` is pretty clear. However some keys are entirely undescriptive, e.g. `TotalJobCPU`. I need some help interpreting this data structure to build the [WMArchive performance data service](https://github.com/knly/WMArchiveAggregation/blob/master/README.md).

This actually applies to the entire FWJRs: A documentation of their data structure would help a lot. In particular I also would like to provide descriptive names for `errorCode`s in the UI.

**Comment by vkuznet** [comment]
Alan,
my understanding that Nils needs to know units for every attribute along with
their description. Some attributes are clear but other are not obvious.
Valentin.

**Comment by vkuznet** [comment]
@amaltaro @ticoann Alan, Seangchan do we need this? If not, please comment/close the issue

**Comment by ticoann** [comment]
I think this can be closed since Nils mainly wants to know the units for each parameter.
