### ISSUE TITLE
Add filter for aggregation getting only final fwjr

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMArchive#224]
Currently archive contains all the fwjr even though it get eventually successful.

i.e
Below documents in meta_data fields (extracting from the 2 different documents in WMArchive data). fwjr_id  contains the same prefix 1234- which considered as the same job but retried.
It might be useful only gets the aggregated statistics for the final case (in this case  "fwjr_id": "1234-1").

```
"meta_data": {
    ...
    "fwjr_id": "1234-0", 
    "host": "vocms001.cern.ch", 
    "agent_ver": "1.0.16.pre1", 
    ... 
}, 

....
"meta_data": {
    ...
    "fwjr_id": "1234-1", 
    "host": "vocms001.cern.ch", 
    "agent_ver": "1.0.16.pre1", 
    ... 
}, 

```

Need to make following assumption.
1. Only failed jobs will be retried. so if a job is successful only  one job report is created. (with the post fix "-0")
2. new fwjr will be created when job is eventually failed or succeed.  (currently set to do 3 retry but this could be changed although unlikely), So in current setting "-2" post fix indicate the last tried job in failed case. Success case it could be any post fix between -0 to -2. 
3. **One important thing to consider fwjr_id alone can't be used. Different document can have the same fwjr_id, so it need to consider "host"  and "agent_version" as well do look for the same job.**

Following two documents cannot be combined since it has different version.

```
"meta_data": {
    ...
    "fwjr_id": "1234-0", 
    "host": "vocms001.cern.ch", 
    "agent_ver": "1.0.16.pre1", 
    ... 
}, 

....
"meta_data": {
    ...
    "fwjr_id": "1234-1", 
    "host": "vocms001.cern.ch", 
    "agent_ver": "1.0.17.pre1", 
    ... 
}, 

```

**Comment by ticoann** [comment]
@amaltaro, Alan please review the issue and feel free to modify or clarify. Thanks

**Comment by amaltaro** [comment]
Everything is correct! I just wanted to complement on 

> new fwjr will be created when job is eventually failed or succeed. (currently set to do 3 retry but this could be changed although unlikely), So in current setting "-2" post fix indicate the last tried job in failed case. Success case it could be any post fix between -0 to -2. 

The number of retries can change in a job type basis or agent basis. Such that we could have a final retry in -3. So better getting the highest number for the retry, no matter what it is.

**Comment by vkuznet** [comment]
@ticoann , @amaltaro do we need something from this issue. Seems to me it just internal discussion between you too and nothing needs to be done in WMArchive, if os please confirm and close the issue

**Comment by vkuznet** [comment]
Closing this issue
