### ISSUE TITLE
Document keys used in WMArchive

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMArchive#225]
Create a json file that document keys used in WMArchive. UI will read from this json file to show defination of the metrics when mouse is moving on them. @vkuznet please let me know where in the repository to store this file. I will first put the performance keys there.

**Comment by vkuznet** [comment]
Yuyi,
we have WMArchive/src/maps/ area where you can put a json file. Once it is in
github we can move it to another location easily.
Valentin.

**Comment by vkuznet** [comment]
@yuyiguo Yuyi, could you please resolve this issue.

**Comment by yuyiguo** [comment]
@vkuznet ,

The metrics was created a while gao. I provided Nils the information and he made the file below, I am closing this issue now.
https://github.com/dmwm/WMArchive/blob/master/src/maps/metrics.json
