### ISSUE TITLE
UI request from Jen

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/WMArchive#235]
Jen would like see below plots, but we don't have data for 3. 1 and 2 should be easy to add.
1.  Distribution of the number of errors by time, by sites filtered by workflow name.
2.  ErrorCode changes vs time filtered by workflow.  
3.  The number of CPU cores.

**Comment by vkuznet** [comment]
Yuyi, I think we need further clarification. What exactly Jen meant by number of errors? The default plot we have shows job state (success, failed) vs time. In my mind it shows number of errors (the red part of the plot). The filters are clear though, e.g. the plot should show only errors vs time for a given site. So, I'll suggest that you'll clarify with Jen #1.

For #2, I'll not say that it's **easy** to add, first we need to learn MongoDB aggregation pipeline syntax which Nils used in a code, but here is a first attempt:

```
db.performance.aggregate([{$match:{"scope.exitCode":{$ne:null}}}, { $project : { ddate: { $dateToString : {format: "%Y-%m-%d", date:"$scope.start_date"} }, dcode:"$scope.exitCode", _id:0} }, {$group: {_id:"$ddate", total:{$sum:1}} }, {$sort: {"_id":1}} ])
{ "_id" : "2016-08-14", "total" : 115 }
{ "_id" : "2016-08-15", "total" : 107 }
{ "_id" : "2016-08-16", "total" : 68 }
{ "_id" : "2016-08-17", "total" : 111 }
{ "_id" : "2016-08-18", "total" : 104 }
```

so it shows a query which we need to impose in order to get distribution of (total number of ) exitCodes by time. Again the filter will be easy to add. Please clarify with Jen if this is what she wants.

**Comment by yuyiguo** [comment]
Hi, @vkuznet 
I talked with Jen. Here is what she wants to debug some of her problems.  She wants the number of a exitCode changes with time and filtered by workflow or  by site.

One example she had was that when a workflow failed, she wanted to know what caused it.   Say if it was a file reading problem, she wanted to know which sites had the problem.

**Comment by vkuznet** [comment]
Yuyi, I made preliminary changes for exit codes. Could you please have a look at testbed. You need to choose in left columns the ExitCodes (see under Data/Events) and new plot will pop-up in dashboard. It will show exit code evolution. The graphs shows all not null exit codes by default. But user can choose specific exit code from filters drop-down menu. If you have trouble here is a URL i used: http://bit.ly/2ephntx

**Comment by yuyiguo** [comment]
@vkuznet 
it looks good to me. I think Jen will like it too.
I found that if I chose one exit code, say 70318, the site list will only show T1_IT_CNF and T1_US_FNAL_DISK.  So the sites were pre filtered to only show relevant sites. Is this a new feature? I did not notice this before. 
I also saw you put per host, per job state besides of site. This is great !

**Comment by jenimal** [comment]
I'm trying to drill in to find the exit code that is most common and am just getting "object object"  I have my filters set to:
Workflow: pdmvserv_BPH-RunIISummer15GS-00077_00448_v0__161019_161203_3148
site = empty so object object
job type production
job state : jobfailed

**Comment by vkuznet** [comment]
It should be done differently, so far I implemented aggregation over all non-zero exit codes, but I didn't keep track of exitcodes themselves. As I posted above, the aggregated records looks like:

```
{ "_id" : "2016-08-14", "total" : 115 }
```

which means that individual codes are lost in aggregation. To do that we need 3D plot, where one axis shows time, another total number for specific code and third the code id. But I think it is too much. Instead you can look at individual codes. Use your conditions and then select specific Exit Code filter. I understand that it may be not optimal but once you scan all codes you'll find the one you're looking for.

**Comment by vkuznet** [comment]
@yuyi, @jenimal , please check testbed site again since I fixed exitcode vs site,host,jobstate plots which now correctly shows values instead of string "object".

**Comment by yuyiguo** [comment]
@vkuznet @jenimal 
It looked good to me. I tried all except for workflow because I did not have a valid workflow name.

**Comment by jenimal** [comment]
OK here is a valid workflow name:
pdmvserv_BPH-RunIISummer15GS-00080_00448_v0__161019_161345_989
that was reported as having lots of exit code "134" in Dashboard yesterday.. meaning no job report.. of course WmAgent was giving a different exit code.. but let's see if we can see the errors i WMArchive... 
https://cmsweb-testbed.cern.ch/wmarchive/web/performance?metrics[]=data.events&metrics[]=data.exitcodes&metrics[]=jobstate&metrics[]=memory.PeakValueRss&axes[]=host&axes[]=jobstate&axes[]=site&start_date=20161023&end_date=20161025&workflow=pdmvserv_BPH-RunIISummer15GS-00080_00448_v0__161019_161345_989

Now to start playing with filters to figure out exactly what we want to look at

**Comment by jenimal** [comment]
OK trying to drill in to get the number of failures, for a specific exit code for a specific workflow over time.  
Here is an example:
for workflow:
pdmvserv_TRK-TTI2023Upg14D-00008_00006_v1__161010_155833_1597
which is currently in production, and has had failures for the last few days 
Looking in WMStats, I see thousands of jobs in cooloff with the error codes:
8002
134
92

and others, those are the biggies that would possibly point to site issues.
For each code, a plot of the number of failures over time.

**Comment by vkuznet** [comment]
Jen, I don't see these code at all in WMArchive exit code list, let's ask Alan @amaltaro and Seangchan @ticoann about them. I don't know what they're and if they were ever written to WMArchive.

**Comment by vkuznet** [comment]
Code to show exitCode evolution was presented in #243

**Comment by vkuznet** [comment]
This request has been implemented in current production release. All exitCodes follow WMStats logic.
