### ISSUE TITLE
Don't use json.dump when respond is returned.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMArchive#96]
Just use python dict, REST code will automatically encode depending on the header "Accept" from request.

When client decode json str, it get list of str instead of list of dictionary.
['{"status": "ok", "ids": ["b51484a168677e16660ea00250fa8036"], "stype": "mongodb"}']

**Comment by vkuznet** [comment]
Seangchan, our emails cross, I just fixed the problem here:
https://github.com/dmwm/WMArchive/pull/98
Please review.
